import { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { motion, MotionConfig } from "framer-motion";
import { ArrowLeft, Clock, Users, ChefHat, Check, Share2, Printer, MessageCircle, Download, Copy, MoreHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useToast } from "@/hooks/use-toast";

// Print styles
const printStyles = `
  @media print {
    body * {
      visibility: hidden;
    }
    
    .print-content, .print-content * {
      visibility: visible;
    }
    
    .print-content {
      position: absolute;
      left: 0;
      top: 0;
      width: 100%;
    }
    
    .no-print {
      display: none !important;
    }
    
    .print-only {
      display: block !important;
    }
    
    @page {
      margin: 1in;
      size: A4;
    }
  }
`;

interface Ingredient {
  name: string;
  quantity: number;
  unit: string;
  notes?: string;
}

interface Step {
  stepNumber: number;
  instruction: string;
}

interface Recipe {
  id: number;
  slug?: string;
  name: string;
  description: string;
  servings: number;
  prepTimeMinutes?: number;
  cookTimeMinutes: number;
  totalTimeMinutes?: number;
  difficulty: string;
  cuisine?: string;
  mealType?: string;
  tags: string[];
  ingredients: Ingredient[];
  steps: Step[];
  imageUrl: string;
  author?: {
    name: string;
    isAI?: boolean;
  };
  rating?: number;
  ratingCount?: number;
  createdAt?: string;
  sourceUrl?: string;
}

const RecipeDetailPage = () => {
  const { id } = useParams<{ id: string }>();
  const [recipe, setRecipe] = useState<Recipe | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast();

  useEffect(() => {
    const loadRecipe = async () => {
      try {
        setLoading(true);
        const response = await fetch('/Recipies.json');
        const data = await response.json();
        
        const foundRecipe = data.recipes.find((r: any) => r.id === parseInt(id || '0'));
        
        if (foundRecipe) {
          // Use slug-based image URLs from assets
          const recipeWithImage = {
            ...foundRecipe,
            imageUrl: `/src/assets/${foundRecipe.name}.jpg`,
          };
          setRecipe(recipeWithImage);
        } else {
          setError("Recipe not found");
        }
      } catch (err) {
        console.error('Error loading recipe:', err);
        setError("Failed to load recipe");
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      loadRecipe();
    } else {
      setError("Invalid recipe ID");
      setLoading(false);
    }
  }, [id]);

  // Enhanced PDF generation function
  const generatePDF = () => {
    if (!recipe) return;
    
    const content = `
${recipe.name}

${recipe.description ? `${recipe.description}\n\n` : ''}

RECIPE DETAILS:
• Servings: ${recipe.servings}
• Cook Time: ${recipe.cookTimeMinutes} minutes
${recipe.prepTimeMinutes ? `• Prep Time: ${recipe.prepTimeMinutes} minutes` : ''}
${recipe.totalTimeMinutes ? `• Total Time: ${recipe.totalTimeMinutes} minutes` : ''}
• Difficulty: ${recipe.difficulty}
${recipe.cuisine ? `• Cuisine: ${recipe.cuisine}` : ''}
${recipe.mealType ? `• Meal Type: ${recipe.mealType}` : ''}

INGREDIENTS:
${recipe.ingredients.map(ing => 
  `• ${ing.quantity} ${ing.unit} ${ing.name}${ing.notes ? ` (${ing.notes})` : ''}`
).join('\n')}

INSTRUCTIONS:
${recipe.steps.map(step => 
  `${step.stepNumber}. ${step.instruction}`
).join('\n\n')}

${recipe.tags.length > 0 ? `\nTAGS: ${recipe.tags.join(', ')}` : ''}

Generated by Mix&Match - Your AI Sous Chef
    `;
    
    // Create a blob with the content
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${recipe.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_recipe.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    toast({
      title: "Recipe downloaded! 📄",
      description: "Recipe saved as text file to your device.",
    });
  };

  // Copy recipe link to clipboard
  const copyRecipeLink = async () => {
    if (!recipe) return;
    
    try {
      const recipeUrl = `${window.location.origin}/recipe/${recipe.id}`;
      await navigator.clipboard.writeText(recipeUrl);
      toast({
        title: "Link copied! 📋",
        description: "Recipe link copied to clipboard.",
      });
    } catch (error) {
      toast({
        title: "Copy failed 😕",
        description: "Could not copy link to clipboard.",
        variant: "destructive",
      });
    }
  };

  // Enhanced print function
  const handlePrint = () => {
    try {
      window.print();
      toast({
        title: "Printing recipe! 🖨️",
        description: "Opening print dialog for PDF export.",
      });
    } catch (error) {
      toast({
        title: "Print failed 😕",
        description: "Could not open print dialog. Please try again.",
        variant: "destructive",
      });
    }
  };

  // Share via Web Share API or fallback
  const handleShare = async () => {
    if (!recipe) return;
    
    const shareData = {
      title: recipe.name,
      text: `Check out this amazing recipe: ${recipe.name}${recipe.description ? ` - ${recipe.description}` : ''}`,
      url: `${window.location.origin}/recipe/${recipe.id}`,
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
        toast({
          title: "Recipe shared! 📤",
          description: "Recipe shared successfully.",
        });
      } catch (error) {
        if (error instanceof Error && error.name !== 'AbortError') {
          toast({
            title: "Share failed 😕",
            description: "Could not share recipe.",
            variant: "destructive",
          });
        }
      }
    } else {
      // Fallback to copying link
      await copyRecipeLink();
    }
  };

  if (loading) {
    return (
      <main className="min-h-screen bg-gradient-to-br from-background via-background to-secondary/20 flex items-center justify-center">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="text-center"
        >
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-lg text-muted-foreground">Loading recipe...</p>
        </motion.div>
      </main>
    );
  }

  if (error || !recipe) {
    return (
      <main className="min-h-screen bg-gradient-to-br from-background via-background to-secondary/20 flex items-center justify-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center space-y-6 max-w-md mx-auto px-6"
        >
          <div className="text-6xl mb-4">🍽️</div>
          <h1 className="text-3xl font-bold text-foreground">Recipe Not Found</h1>
          <p className="text-lg text-muted-foreground">
            {error || "The recipe you're looking for doesn't exist or has been moved."}
          </p>
          <Button asChild className="mt-6">
            <Link to="/explore" className="inline-flex items-center gap-2">
              <ArrowLeft className="h-4 w-4" />
              Back to Recipes
            </Link>
          </Button>
        </motion.div>
      </main>
    );
  }

  const fadeInUp = {
    initial: { opacity: 0, y: 12 },
    animate: { opacity: 1, y: 0 },
  };

  const fadeIn = {
    initial: { opacity: 0 },
    animate: { opacity: 1 },
  };

  const staggerContainer = {
    initial: {},
    animate: {
      transition: {
        staggerChildren: 0.05,
      },
    },
  };

  return (
    <MotionConfig reducedMotion="user">
      {/* Print styles */}
      <style dangerouslySetInnerHTML={{ __html: printStyles }} />
      
      <main className="min-h-screen bg-gradient-to-br from-background via-background/95 to-secondary/10">
        <div className="container mx-auto px-4 py-6 max-w-7xl">
          {/* Back Link */}
          <motion.nav
            initial={{ opacity: 0, x: -12 }}
            animate={{ opacity: 1, x: 0 }}
            className="mb-6 no-print"
          >
            <Button 
              variant="ghost" 
              asChild 
              className="gap-2 text-muted-foreground hover:text-foreground focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2" 
              aria-label="Go back to Explore recipes"
            >
              <Link to="/explore">
                <ArrowLeft className="h-4 w-4" />
                Back to Explore
              </Link>
            </Button>
          </motion.nav>

          {/* Top Chip Row */}
          <motion.header
            variants={fadeInUp}
            initial="initial"
            animate="animate"
            transition={{ duration: 0.4 }}
            className="mb-6 no-print"
            aria-labelledby="recipe-meta"
          >
            <div className="flex flex-wrap gap-2">
              {recipe.cuisine && (
                <Badge variant="outline" className="bg-primary/5 border-primary/20 text-primary font-medium">
                  {recipe.cuisine.charAt(0).toUpperCase() + recipe.cuisine.slice(1)}
                </Badge>
              )}
              {recipe.mealType && (
                <Badge variant="outline" className="bg-secondary/5 border-secondary/20 text-secondary-foreground font-medium">
                  {recipe.mealType.charAt(0).toUpperCase() + recipe.mealType.slice(1)}
                </Badge>
              )}
              {recipe.tags.filter(tag => ['vegan', 'vegetarian', 'gluten-free', 'dairy-free', 'keto', 'paleo'].includes(tag)).map((tag) => (
                <Badge key={tag} variant="secondary" className="font-medium capitalize">
                  {tag}
                </Badge>
              ))}
            </div>
          </motion.header>

          {/* Two-Column Layout */}
          <div className="grid lg:grid-cols-5 gap-8 recipe-content">
            {/* Left Column - Sticky Hero Card */}
            <motion.aside
              variants={fadeInUp}
              initial="initial"
              animate="animate"
              transition={{ duration: 0.5 }}
              className="lg:col-span-2 lg:sticky lg:top-6 lg:h-fit no-print"
            >
              <Card className="overflow-hidden border-2 shadow-xl bg-gradient-to-br from-card/95 to-card/80 backdrop-blur-sm">
                <div className="relative h-80 md:h-96 lg:h-[28rem] xl:h-[32rem] recipe-image">
                  <img
                    src={recipe.imageUrl}
                    alt={`${recipe.name} - Recipe hero image`}
                    className="w-full h-full object-cover"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-black/20 to-transparent" />
                  
                  {/* Meta Pills */}
                  <div className="absolute bottom-4 left-4 right-4">
                    <div className="flex flex-wrap gap-2">
                      {recipe.cookTimeMinutes && (
                        <div className="flex items-center gap-2 bg-white/15 backdrop-blur-md px-3 py-2 rounded-full text-white text-sm font-medium border border-white/20">
                          <Clock className="h-4 w-4" />
                          {recipe.cookTimeMinutes} min
                        </div>
                      )}
                      {recipe.servings && (
                        <div className="flex items-center gap-2 bg-white/15 backdrop-blur-md px-3 py-2 rounded-full text-white text-sm font-medium border border-white/20">
                          <Users className="h-4 w-4" />
                          Serves {recipe.servings}
                        </div>
                      )}
                      {recipe.difficulty && (
                        <div className="flex items-center gap-2 bg-white/15 backdrop-blur-md px-3 py-2 rounded-full text-white text-sm font-medium border border-white/20">
                          <ChefHat className="h-4 w-4" />
                          {recipe.difficulty.charAt(0).toUpperCase() + recipe.difficulty.slice(1)}
                        </div>
                      )}
                    </div>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="px-6 py-4 bg-gradient-to-r from-background/95 via-background/90 to-background/95 border-t border-border/30">
                  <div className="flex gap-2">
                    <Button 
                      variant="outline" 
                      size="sm" 
                      className="flex-1 gap-2 hover:bg-blue-50 hover:text-blue-600 transition-colors duration-200"
                      onClick={handleShare}
                    >
                      <Share2 className="h-4 w-4" />
                      Share
                    </Button>
                    <Button 
                      variant="outline" 
                      size="sm" 
                      className="flex-1 gap-2 hover:bg-orange-50 hover:text-orange-600 transition-colors duration-200"
                      onClick={() => {
                        try {
                          const redditUrl = `https://www.reddit.com/submit?title=${encodeURIComponent(recipe.name)}&url=${encodeURIComponent(window.location.href)}`;
                          window.open(redditUrl, '_blank');
                          toast({
                            title: "Opening Reddit! 🤖",
                            description: "Redirecting to Reddit to share this recipe.",
                          });
                        } catch (error) {
                          toast({
                            title: "Reddit share failed 😕",
                            description: "Could not open Reddit. Please try again.",
                            variant: "destructive",
                          });
                        }
                      }}
                    >
                      <MessageCircle className="h-4 w-4" />
                      Reddit
                    </Button>
                    
                    {/* Enhanced Export Dropdown */}
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button 
                          variant="outline" 
                          size="sm" 
                          className="gap-2 hover:bg-green-50 hover:text-green-600 transition-colors duration-200"
                        >
                          <MoreHorizontal className="h-4 w-4" />
                          Export
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end" className="w-48">
                        <DropdownMenuItem onClick={handlePrint} className="gap-3">
                          <Printer className="h-4 w-4" />
                          Print Recipe
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={generatePDF} className="gap-3">
                          <Download className="h-4 w-4" />
                          Download PDF
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem onClick={copyRecipeLink} className="gap-3">
                          <Copy className="h-4 w-4" />
                          Copy Link
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                </div>

                <CardContent className="p-6 space-y-4">
                  <div>
                    <h1 className="text-2xl lg:text-3xl font-bold text-foreground leading-tight mb-3 recipe-title">
                      {recipe.name}
                    </h1>
                    <p className="text-muted-foreground leading-relaxed text-sm lg:text-base mb-4">
                      {recipe.description}
                    </p>
                    
                    {/* Quick Recipe Details - Integrated */}
                    <div className="grid grid-cols-2 gap-3 mb-4 text-sm">
                      <div className="flex items-center justify-between p-2 bg-background/50 rounded-lg">
                        <span className="text-muted-foreground">Total Time</span>
                        <span className="font-medium">
                          {(recipe.prepTimeMinutes || 0) + recipe.cookTimeMinutes} min
                        </span>
                      </div>
                      <div className="flex items-center justify-between p-2 bg-background/50 rounded-lg">
                        <span className="text-muted-foreground">Difficulty</span>
                        <Badge className="capitalize text-xs bg-green-100 text-green-700 border-green-200 hover:bg-green-200">
                          {recipe.difficulty}
                        </Badge>
                      </div>
                      {recipe.cuisine && (
                        <div className="flex items-center justify-between p-2 bg-background/50 rounded-lg">
                          <span className="text-muted-foreground">Cuisine</span>
                          <Badge className="capitalize text-xs bg-blue-100 text-blue-700 border-blue-200 hover:bg-blue-200">
                            {recipe.cuisine}
                          </Badge>
                        </div>
                      )}
                      {recipe.mealType && (
                        <div className="flex items-center justify-between p-2 bg-background/50 rounded-lg">
                          <span className="text-muted-foreground">Meal Type</span>
                          <Badge className="capitalize text-xs bg-purple-100 text-purple-700 border-purple-200 hover:bg-purple-200">
                            {recipe.mealType}
                          </Badge>
                        </div>
                      )}
                    </div>
                    
                    {/* Rating & Author */}
                    <div className="flex items-center justify-between mb-4">
                      <div className="flex items-center gap-2">
                        {recipe.rating && (
                          <div className="flex items-center gap-1">
                            <span className="text-yellow-500">{'★'.repeat(Math.floor(recipe.rating))}</span>
                            <span className="text-sm font-medium">{recipe.rating}</span>
                            {recipe.ratingCount && (
                              <span className="text-xs text-muted-foreground">({recipe.ratingCount})</span>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* All Recipe Tags - Better Integration */}
                  <div className="flex flex-wrap gap-2 pt-4 border-t border-border/30">
                    {recipe.tags.slice(0, 8).map((tag, index) => (
                      <Badge
                        key={tag}
                        className={`text-xs font-medium capitalize transition-colors ${
                          index % 4 === 0 ? 'bg-orange-100 text-orange-700 border-orange-200 hover:bg-orange-200' :
                          index % 4 === 1 ? 'bg-teal-100 text-teal-700 border-teal-200 hover:bg-teal-200' :
                          index % 4 === 2 ? 'bg-emerald-100 text-emerald-700 border-emerald-200 hover:bg-emerald-200' :
                          'bg-indigo-100 text-indigo-700 border-indigo-200 hover:bg-indigo-200'
                        }`}
                      >
                        {tag.replace('-', ' ')}
                      </Badge>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </motion.aside>

            {/* Right Column - Scrollable Content */}
            <motion.div
              variants={staggerContainer}
              initial="initial"
              animate="animate"
              className="lg:col-span-3 space-y-6 print-content"
            >
              {/* Print-only header */}
              <div className="print-only hidden">
                <h1 className="text-3xl font-bold mb-4">{recipe.name}</h1>
                {recipe.description && (
                  <p className="text-lg text-muted-foreground mb-6">{recipe.description}</p>
                )}
                <div className="grid grid-cols-3 gap-4 mb-8 text-sm">
                  <div>
                    <strong>Servings:</strong> {recipe.servings}
                  </div>
                  <div>
                    <strong>Cook Time:</strong> {recipe.cookTimeMinutes} min
                  </div>
                  <div>
                    <strong>Difficulty:</strong> {recipe.difficulty}
                  </div>
                </div>
              </div>

              {/* Ingredients Section */}
              <motion.section 
                variants={fadeInUp}
                aria-labelledby="ingredients-heading"
              >
                <Card className="border-2 shadow-lg bg-gradient-to-br from-card/95 to-card/80 backdrop-blur-sm hover:shadow-xl transition-shadow duration-300">
                  <CardContent className="p-6">
                    <h2 id="ingredients-heading" className="text-xl font-bold mb-5 flex items-center gap-3">
                      🥘 Ingredients
                      <span className="text-sm font-normal text-muted-foreground">
                        ({recipe.ingredients.length} items)
                      </span>
                    </h2>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {recipe.ingredients.map((ingredient, index) => (
                        <motion.div
                          key={index}
                          variants={fadeIn}
                          className="flex items-start gap-3 p-4 rounded-lg bg-muted/20 hover:bg-muted/40 transition-colors group border border-border/20 hover:border-primary/20"
                        >
                          <button 
                            className="flex-shrink-0 w-5 h-5 bg-primary/10 border-2 border-primary/30 rounded-sm flex items-center justify-center mt-0.5 hover:bg-primary/20 focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 transition-colors"
                            aria-label={`Mark ${ingredient.name} as completed`}
                          >
                            <Check className="h-3 w-3 text-primary opacity-0 group-hover:opacity-100 transition-opacity" />
                          </button>
                          <div className="flex-1 min-w-0">
                            <div className="font-medium text-foreground">
                              <span className="text-primary font-semibold">{ingredient.quantity} {ingredient.unit}</span>
                              <span className="ml-2">{ingredient.name}</span>
                            </div>
                            {ingredient.notes && (
                              <span className="text-sm text-muted-foreground block mt-1 italic">
                                {ingredient.notes}
                              </span>
                            )}
                          </div>
                        </motion.div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              </motion.section>

              {/* Instructions Section */}
              <motion.section 
                variants={fadeInUp}
                aria-labelledby="instructions-heading"
              >
                <Card className="border-2 shadow-lg bg-gradient-to-br from-card/95 to-card/80 backdrop-blur-sm hover:shadow-xl transition-shadow duration-300">
                  <CardContent className="p-6">
                    <h2 id="instructions-heading" className="text-xl font-bold mb-5 flex items-center gap-3">
                      👨‍🍳 Instructions
                      <span className="text-sm font-normal text-muted-foreground">
                        ({recipe.steps.length} steps)
                      </span>
                    </h2>
                    <div className="space-y-4">
                      {recipe.steps.map((step, index) => (
                        <motion.div
                          key={step.stepNumber}
                          variants={fadeIn}
                          className="flex items-start gap-4 p-4 rounded-lg hover:bg-muted/30 transition-colors border border-border/30"
                        >
                          <span className="flex-shrink-0 w-8 h-8 bg-primary text-primary-foreground rounded-full flex items-center justify-center font-bold text-sm shadow-sm">
                            {step.stepNumber}
                          </span>
                          <div className="flex-1 pt-1">
                            <p className="text-foreground leading-relaxed">
                              {step.instruction}
                            </p>
                            {/* Add estimated time for steps if available */}
                            {index === 0 && recipe.prepTimeMinutes && (
                              <div className="mt-2">
                                <Badge variant="outline" className="text-xs">
                                  Prep: ~{Math.ceil(recipe.prepTimeMinutes / recipe.steps.length)} min
                                </Badge>
                              </div>
                            )}
                          </div>
                        </motion.div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              </motion.section>
            </motion.div>
          </div>
        </div>
      </main>
    </MotionConfig>
  );
};

export default RecipeDetailPage;
